#!/bin/bash

# USAGE: setup-
# -c Class Code`

while getopts c:r: option
do
case "${option}"
in
c) CLASS=${OPTARG};;
r) CLASS_REPO=${OPTARG};;
esac
done

if [ ! "$CLASS" ]; then
   echo "Class Code Required"
   exit 2
fi

if [ ! "$CLASS_REPO" ]; then
   echo "Class Repository Required"
   exit 2
fi

GUIDE=git@github.com:codefellows/code-401-javascript-guide.git
GUIDE_NAME=code-401-javascript-guide.git

mkdir scratch
cd scratch || exit

git clone --bare $GUIDE

cd $GUIDE_NAME || exit

git push --mirror $CLASS_REPO

cd ../..
rm -rf scratch


## Clone the new copy
git clone $CLASS_REPO ./$CLASS

## Reconfigure .gitignore
cd $CLASS || exit

## Send up the new .gitignore so we don't push facilitator stuff to the class.
cat >> .gitignore <<EOL
# 401JS Guide
solution
facilitator
apps-and-libraries
extra-content
setup-401-js
student-comments.md
/README.md
**/demo/README.md
FACILITATOR.md
EOL

git add .
git commit -m "Updated .gitignore"
git push origin master

## Clear out the repo, and then push it clean (force obey .gitignore)
git rm -r --cached .
git add .
git commit -m "Clear Out the Guide Fluff"
git push origin master

# Connect to the guide as an upstream
git remote add upstream $GUIDE
